Assignment_2_(MVC)_CodeFirst/Models/Entities/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Assignment_2__MVC__CodeFirst.Models.Entities
{
    public class Student : IEntity
    {
        public int ID { get; set; }

        [Required]
        [MinLength(3)]
        public string FirstName { get; set; }

        [Required]
        [MinLength(3)]
        public string LastName { get; set; }

        [NotMapped]
        public string FullName { get => $"{this.FirstName} {this.LastName}"; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true)]
        //[CurrentDate(ErrorMessage = "Date must be after or equal to current date")]
        public DateTime StartDate { get; set; }

        [Required]
        public School School { get; set; }

        public ICollection<Course> Courses { get; set; } = new List<Course>();

        public ICollection<Assignment> Assignments { get; set; } = new List<Assignment>();
    }
}

Assignment_2_(MVC)_CodeFirst/ViewModels/StudentViewModel.cs
using Assignment_2__MVC__CodeFirst.Models.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Assignment_2__MVC__CodeFirst.ViewModels
{
    public class StudentViewModel
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime StartDate { get; set; }
        public int SchoolId { get; set; }
        public IEnumerable<int> SelectedCourses { get; set; }
        public IEnumerable<int> SelectedAssignments { get; set; }
        public IEnumerable<Course> MyCourses { get; set; }
        public IEnumerable<Assignment> MyAssignments { get; set; }
        public IEnumerable<SelectListItem> Courses { get; set; }
        public IEnumerable<SelectListItem> Assignments { get; set; }
        public SelectList Schools { get; set; }
    }
}

Assignment_2_(MVC)_CodeFirst/Controllers/Api/StudentsController.cs
using Assignment_2__MVC__CodeFirst.Models.Dto;
using Assignment_2__MVC__CodeFirst.Models.Entities;
using Assignment_2__MVC__CodeFirst.Models.Other;
using Assignment_2__MVC__CodeFirst.Static;
using AutoMapper;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Http;

namespace Assignment_2__MVC__CodeFirst.Controllers.Api
{
    public class StudentsController : ApiController, IMyController<IHttpActionResult, StudentDto>
    {
        [HttpPost]
        public IHttpActionResult Create(StudentDto studentDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var student = Mapper.Map<StudentDto, Student>(studentDto);
            Repos.studentRepo.Add(student);
            Repos.DbHundler.Save();
            return Ok(studentDto);
        }
        [HttpDelete]
        public IHttpActionResult Delete(int id)
        {
            var student = Repos.studentRepo.Get(id);
            if (student == null)
                return BadRequest();
            Repos.studentRepo.Delete(student);
            Repos.DbHundler.Save();
            var studentDto = Mapper.Map<Student, StudentDto>(student);
            return Ok(studentDto);
        }
        [HttpGet]
        public IHttpActionResult Get(int id)
        {
            var student = Repos.studentRepo.GetEmpty(id);
            if (student == null)
                return NotFound();
            var studentDto = Mapper.Map<Student, StudentDto>(student);
            return Ok(studentDto);
        }
        [HttpGet]
        public IHttpActionResult GetAll()
        {
            var students = Repos.studentRepo.GetAllEmpty().Select(Mapper.Map<Student, StudentDto>);
            return Ok(students);
        }
        [HttpPut]
        public IHttpActionResult Update(int id, StudentDto studentDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var student = Repos.studentRepo.Get(id);
            if (student == null)
                return NotFound();
            Mapper.Map(studentDto, student);
            Repos.DbHundler.Save();
            return StatusCode(HttpStatusCode.NoContent);
        }
        [Route("api/Students/RemoveCourse"), HttpPost]
        public async Task<IHttpActionResult> RemoveCourseAsync([FromBody] StudentCourseData data)
        {
            if (data.studentId == null || data.courseId == null)
                return BadRequest();
            Student student = Repos.studentRepo.Get(data.studentId);
            Course course = Repos.courseRepo.Get(data.courseId);
            if (student == null || course == null)
                return BadRequest();
            student.Courses.Remove(course);
            course.Students.Remove(student);
            if (ModelState.IsValid)
            {
                Repos.studentRepo.Update(student);
                Repos.courseRepo.Update(course);
                _ = await Repos.DbHundler.SaveAsync();
                return Ok(200);
            }
            return BadRequest("Record Failed");
        }
        [Route("api/Students/RemoveAssignment"), HttpPost]
        public async Task<IHttpActionResult> RemoveAssignmentAsync([FromBody] StudentAssignmentData data)
        {
            if (data.studentId == null || data.assignmentId == null)
                return BadRequest();
            Student student = Repos.studentRepo.Get(data.studentId);
            Assignment assignment = Repos.assignmentRepo.Get(data.assignmentId);
            if (student == null || assignment == null)
                return BadRequest();
            student.Assignments.Remove(assignment);
            assignment.Students.Remove(student);
            if (ModelState.IsValid)
            {
                Repos.studentRepo.Update(student);
                Repos.assignmentRepo.Update(assignment);
                _ = await Repos.DbHundler.SaveAsync();
                return Ok(200);
            }
            return BadRequest("Record Failed");
        }
        [Route("api/Students/AddCourse"), HttpPost]
        public async Task<IHttpActionResult> AddCoursesAsync([FromBody] List<StudentCourseData> data)
        {
            if (data.Count == 0)
                return BadRequest("data.Count == 0");
            var student = Repos.studentRepo.GetEmpty(data[0].studentId);
            if (student == null)
                return BadRequest("student == null");
            var coursesIds = data.Select(d => d.courseId).ToList();
            var courses = Repos.courseRepo.GetAllByIdsEmpty(coursesIds);
            foreach (var course in courses)
            {
                student.Courses.Add(course);
            }
            _ = await Repos.DbHundler.SaveAsync();
            return Ok(200);
        }
        [Route("api/Students/AddAssingment"), HttpPost]
        public async Task<IHttpActionResult> AddAssignmentsAsync([FromBody] List<StudentAssignmentData> data)
        {
            if (data.Count == 0)
                return BadRequest("data.Count == 0");
            var student = Repos.studentRepo.GetEmpty(data[0].studentId);
            if (student == null)
                return BadRequest("student == null");
            var assignmentsIds = data.Select(d => d.assignmentId).ToList();
            var assignments = Repos.assignmentRepo.GetAllByIdsEmpty(assignmentsIds);
            foreach (var assignment in assignments)
            {
                student.Assignments.Add(assignment);
            }
            _ = await Repos.DbHundler.SaveAsync();
            return Ok(200);
        }
    }
}

Assignment_2_(MVC)_CodeFirst/Controllers/CoursesController.cs
using Assignment_2__MVC__CodeFirst.Models.Entities;
using Assignment_2__MVC__CodeFirst.Repositories;
using Assignment_2__MVC__CodeFirst.Static;
using Assignment_2__MVC__CodeFirst.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Assignment_2__MVC__CodeFirst.Controllers
{
    public class CoursesController : Controller
    {
        private Repos _repositories;
        private CourseRepo _courseRepo;
        private SchoolRepo _schoolRepo;
        private TrainerRepo _trainerRepo;
        private StudentRepo _studentRepo;
        public CoursesController(IRepos repo)
        {
            this._repositories = (Repos)repo;
            this._courseRepo = this._repositories.Courses;
            this._schoolRepo = this._repositories.Schools;
            this._trainerRepo = this._repositories.Trainers;
            this._studentRepo = this._repositories.Students;
        }
        // GET: Courses
        public ActionResult Index()
        {
            return View(this._courseRepo.GetAll());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(string Search)
        {
            if (Search != null && Search.Length > 0)
                return View(this._courseRepo.GetAllByName(Search));
            else
                return View(this._courseRepo.GetAll());
        }

        // GET: Courses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = this._courseRepo.Get(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // GET: Courses/Create
        public ActionResult Create(int schoolId)
        {
            var schools = new SelectList(this._schoolRepo.GetAll(), "ID", "Name");
            var trainers = new SelectList(this._trainerRepo.GetAllBySchool(schoolId), "ID", "FullName");
            List<SelectListItem> studentsSelectListItems = new List<SelectListItem>();
            foreach (Student student in this._studentRepo.GetAllBySchool(schoolId))
            {
                SelectListItem selectList = new SelectListItem()
                {
                    Text = student.FullName,
                    Value = student.ID.ToString()
                };
                studentsSelectListItems.Add(selectList);
            }

            CourseViewModel courseView = new CourseViewModel()
            {
                SelectedStudents = new List<int>(),
                Students = studentsSelectListItems,
                SchoolId = schoolId,
                Schools = schools,
                Trainers = trainers
            };

            return View(courseView);
        }

        // POST: Courses/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CourseViewModel courseView)
        {
            Course course = new Course();
            course.Title = courseView.Title;
            course.StartDate = courseView.StartDate;
            course.EndDate = courseView.EndDate;
            course.School = this._schoolRepo.Get(courseView.SchoolId);
            course.Trainer = this._trainerRepo.Get(courseView.TrainerId);
            if (courseView.SelectedStudents != null)
            {
                var students = this._studentRepo.GetAllBySchool(course.School.ID);
                foreach (var id in courseView.SelectedStudents)
                {
                    var selectedStudent = this._studentRepo.Get(id);
                    if (students.Contains(selectedStudent))
                    {
                        if (course.Students != null)
                        {
                            course.Students.Add(selectedStudent);
                        }
                        else
                        {
                            course.Students = new List<Student>();
                            course.Students.Add(selectedStudent);
                        }
                    } 
                }
            }

            if (ModelState.IsValid)
            {
                this._courseRepo.Add(course);
                this._courseRepo.Save();
                return RedirectToAction("Details", "Schools", new { id = course.School.ID });
            }

            return View(courseView);
        }

        // GET: Courses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Course course = this._courseRepo.Get(id);
            if (course == null)
                return HttpNotFound();

            var schools = new SelectList(this._schoolRepo.GetAll(), "ID", "Name");
            var selectedSchool = schools.FirstOrDefault(x => int.Parse(x.Value) == course.ID);
            if (selectedSchool != null) selectedSchool.Selected = true;

            var trainers = new SelectList(this._trainerRepo.GetAllBySchool(course.School.ID), "ID", "FullName");
            var selectedTrainer = trainers.FirstOrDefault(x => int.Parse(x.Value) == course.ID);
            if (selectedTrainer != null) selectedTrainer.Selected = true;

            List<SelectListItem> studentsSelectListItems = new List<SelectListItem>();
            foreach (Student student in this._studentRepo.GetAllBySchool(course.School.ID))
            {
                SelectListItem selectList = new SelectListItem()
                {
                    Text = student.FullName,
                    Value = student.ID.ToString()
                };
                if (!course.Students.Contains(student))
                    studentsSelectListItems.Add(selectList);
            }

            CourseViewModel courseView = new CourseViewModel()
            {
                ID = course.ID,
                Title = course.Title,
                StartDate = course.StartDate,
                EndDate = course.EndDate,
                SchoolId = course.School.ID,
                TrainerId = course.Trainer.ID,
                SelectedStudents = new List<int>(),
                MyStudents = course.Students,
                Students = studentsSelectListItems,
                Schools = schools,
                Trainers = trainers
            };

            return View(courseView);
        }

        // POST: Courses/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CourseViewModel courseView)
        {
            Course courseDB = this._courseRepo.Get(courseView.ID);
            courseDB.Title = courseView.Title;
            courseDB.StartDate = courseView.StartDate;
            courseDB.EndDate = courseView.EndDate;
            courseDB.School = this._schoolRepo.Get(courseView.SchoolId);
            courseDB.Trainer = this._trainerRepo.Get(courseView.TrainerId);
            if(courseView.SelectedStudents != null)
            {
                var students = this._studentRepo.GetAllBySchool(courseDB.School.ID);
                foreach(var id in courseView.SelectedStudents)
                {
                    var selectedStudent = this._studentRepo.Get(id);
                    if (students.Contains(selectedStudent))
                        courseDB.Students.Add(selectedStudent);
                }
            }

            if (ModelState.IsValid)
            {
                this._courseRepo.Update(courseDB);
                this._courseRepo.Save();
                return RedirectToAction("Details", "Schools", new { id = courseDB.School.ID });
            }

            var schools = new SelectList(this._schoolRepo.GetAll(), "ID", "Name");
            var selectedSchool = schools.FirstOrDefault(x => int.Parse(x.Value) == courseDB.ID);
            if (selectedSchool != null) selectedSchool.Selected = true;

            var trainers = new SelectList(this._trainerRepo.GetAllBySchool(courseDB.School.ID), "ID", "FullName");
            var selectedTrainer = trainers.FirstOrDefault(x => int.Parse(x.Value) == courseDB.ID);
            if (selectedTrainer != null) selectedTrainer.Selected = true;

            List<SelectListItem> studentsSelectListItems = new List<SelectListItem>();
            foreach (Student student in this._studentRepo.GetAllBySchool(courseDB.School.ID))
            {
                SelectListItem selectList = new SelectListItem()
                {
                    Text = student.FullName,
                    Value = student.ID.ToString()
                };
                if (!courseDB.Students.Contains(student))
                    studentsSelectListItems.Add(selectList);
            }

            CourseViewModel courseView2 = new CourseViewModel()
            {
                ID = courseDB.ID,
                Title = courseDB.Title,
                StartDate = courseDB.StartDate,
                EndDate = courseDB.EndDate,
                SchoolId = courseDB.School.ID,
                TrainerId = courseDB.Trainer.ID,
                SelectedStudents = new List<int>(),
                MyStudents = courseDB.Students,
                Students = studentsSelectListItems,
                Schools = schools,
                Trainers = trainers
            };

            return View(courseView2);
        }

        // GET: Courses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = this._courseRepo.Get(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

Assignment_2_(MVC)_CodeFirst/Views/Students/Create.cshtml
@model Assignment_2__MVC__CodeFirst.ViewModels.StudentViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Student</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SchoolId, "School", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.SchoolId, Model.Schools as SelectList, "Select School", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.SchoolId, "", new { @class = "text-danger" })
        </div>
    </div>

    <br />

    <div class="form-group">
        @Html.LabelFor(model => model.SelectedCourses, "Add Courses", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.ListBoxFor(model => model.SelectedCourses, Model.Courses, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.SelectedCourses, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SelectedAssignments, "Add Assignments", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.ListBoxFor(model => model.SelectedAssignments, Model.Assignments, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.SelectedAssignments, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" onclick="loadingShow();"/>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back", "Details", "Schools", new { id = @Model.SchoolId }, new { onclick = "loadingShow();" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Assignment_2_(MVC)_CodeFirst/Views/Students/Delete.cshtml
@model Assignment_2__MVC__CodeFirst.Models.Entities.Student

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Student</h4>
    <hr />
    <div class="container">

        <div class="row">
            <div class="col-md-3">
                @Html.DisplayNameFor(model => model.FirstName)
            </div>

            <div class="col-md-9">
                @Html.DisplayFor(model => model.FirstName)
            </div>
        </div>

        <div class="row">
            <div class="col-md-3">
                @Html.DisplayNameFor(model => model.LastName)
            </div>

            <div class="col-md-9">
                @Html.DisplayFor(model => model.LastName)
            </div>
        </div>

        <div class="row">
            <div class="col-md-3">
                @Html.DisplayNameFor(model => model.StartDate)
            </div>

            <div class="col-md-9">
                @Html.DisplayFor(model => model.StartDate)
            </div>
        </div>

    </div>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Delete" class="btn btn-default" /> |
    @Html.ActionLink("Back", "Details", "Schools", new { Id = @Model.School.ID }, new { onclick = "loadingShow();" })
</div>
    }
</div>

Assignment_2_(MVC)_CodeFirst/Views/Students/Details.cshtml
@model Assignment_2__MVC__CodeFirst.Models.Entities.Student

@{
    ViewBag.Title = "Details";
}

<h2>@Model.FullName</h2>

<div>
    <h4>Student</h4>
    <hr />
    <div class="container">

        <div class="ditails-form text-center">
            <div class="row">
                <div class="col-md-3">
                    <label class="font-weight-bold">@Html.DisplayNameFor(model => model.FullName):</label>
                </div>
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.FullName)
                </div>
            </div>

            <div class="row">
                <div class="col-md-3">
                    <label class="font-weight-bold">@Html.DisplayNameFor(model => model.StartDate):</label>
                </div>
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.StartDate)
                </div>
            </div>

            <div class="row">
                <div class="col-md-3">
                    <label class="font-weight-bold">@Html.DisplayNameFor(model => model.School):</label>
                </div>
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.School.Name)
                </div>
            </div>
        </div>

        <br />

        <div class="row">
            <div>
                <label class="font-weight-bold">@Html.DisplayNameFor(model => model.Courses):</label>
                <div class="table-responsive" style="margin-top: 11px;">
                    <table class="table table-striped table-hover">
                        @foreach (var c in Model.Courses)
                        {
                            <tr class="text-center" scope="row">
                                <td scope="col">@Html.ActionLink(c.Title, "Details", "Courses", new { id = c.ID }, new { onclick = "loadingShow();" })</td>
                                <td scope="col">
                                    @Html.ActionLink("Edit", "Edit", "Courses", new { id = c.ID }, new { onclick = "loadingShow();" }) | 
                                    @Html.ActionLink("Delete", "Delete", "Courses", new { id = c.ID }, new { onclick = "loadingShow();" })
                                </td>
                            </tr>
                        }
                    </table>
                </div>
            </div>
        </div>

        <br />

        <div class="row">
            <div>
                <label class="font-weight-bold">@Html.DisplayNameFor(model => model.Assignments):</label>
                <div class="table-responsive" style="margin-top: 11px;">
                    <table class="table table-striped table-hover">
                        @foreach (var a in Model.Assignments)
                        {
                            <tr class="text-center" scope="row">
                                <td scope="col">@Html.ActionLink(a.Title, "Details", "Assignments", new { id = a.ID }, new { onclick = "loadingShow();" })</td>
                                <td scope="col">
                                    @Html.ActionLink("Edit", "Edit", "Assignments", new { id = a.ID }, new { onclick = "loadingShow();" }) | 
                                    @Html.ActionLink("Delete", "Delete", "Assignments", new { id = a.ID }, new { onclick = "loadingShow();" })
                                </td>
                            </tr>
                        }
                    </table>
                </div>
            </div>
        </div>

        <br />

    </div>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }, new { onclick = "loadingShow();" }) |
    @Html.ActionLink("Back", "Details", "Schools", new { id = @Model.School.ID }, new { onclick = "loadingShow();" })
</p>

Assignment_2_(MVC)_CodeFirst/Views/Students/Index.cshtml
@model IEnumerable<Assignment_2__MVC__CodeFirst.Models.Entities.Student>

@{
    ViewBag.Title = "Index";
}

<h2>Students</h2>

<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Index", "Students", FormMethod.Post))
        {
            @Html.AntiForgeryToken();
            @Html.TextBox("Search", "", "", new { placeholder = "Search", @class = "form-input" });
            <input type="submit" name="SaveButton" value="Save" />
        }
    </div>
    <div class="col-md-6">
        <p>
            @Html.ActionLink("Create New", "Create", null, new { onclick = "loadingShow();" })
        </p>
    </div>
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.FullName, "Details", new { id = item.ID }, new { onclick = "loadingShow();" })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }, new { onclick = "loadingShow();" }) | 
            @Html.ActionLink("Delete", "Delete", new { id=item.ID }, new { onclick = "loadingShow();" })
        </td>
    </tr>
}

</table>