Assignment_2_(MVC)_CodeFirst/Models/Entities/Trainer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Assignment_2__MVC__CodeFirst.Models.Entities
{
    public class Trainer : IEntity
    {
        public int ID { get; set; }

        [Required]
        [MinLength(3)]
        public string FirstName { get; set; }

        [Required]
        [MinLength(3)]
        public string LastName { get; set; }

        [NotMapped]
        public string FullName { get => $"{this.FirstName} {this.LastName}"; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true)]
        //[CurrentDate(ErrorMessage = "Date must be after or equal to current date")]
        public DateTime StartDate { get; set; }
        
        public School School { get; set; }

        public ICollection<Course> Courses { get; set; } = new List<Course>();
    }
}

Assignment_2_(MVC)_CodeFirst/ViewModels/TrainerViewModel.cs
using Assignment_2__MVC__CodeFirst.Models.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Assignment_2__MVC__CodeFirst.ViewModels
{
    public class TrainerViewModel
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime StartDate { get; set; }
        public int SchoolId { get; set; }
        public SelectList Schools { get; set; }
        public IEnumerable<int> SelectedCourses { get; set; }
        public IEnumerable<Course> MyCourses { get; set; }
        public IEnumerable<SelectListItem> Courses { get; set; }
    }
}

Assignment_2_(MVC)_CodeFirst/Controllers/Api/TrainersController.cs
using Assignment_2__MVC__CodeFirst.Models.Dto;
using Assignment_2__MVC__CodeFirst.Models.Entities;
using Assignment_2__MVC__CodeFirst.Models.Other;
using Assignment_2__MVC__CodeFirst.Static;
using AutoMapper;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Http;

namespace Assignment_2__MVC__CodeFirst.Controllers.Api
{
    public class TrainersController : ApiController, IMyController<IHttpActionResult, TrainerDto>
    {
        [HttpPost]
        public IHttpActionResult Create(TrainerDto trainerDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var trainer = Mapper.Map<TrainerDto, Trainer>(trainerDto);
            Repos.trainerRepo.Add(trainer);
            Repos.DbHundler.Save();
            return Ok(trainerDto);
        }
        [HttpDelete]
        public IHttpActionResult Delete(int id)
        {
            var trainer = Repos.trainerRepo.Get(id);
            if (trainer == null)
                return NotFound();
            Repos.trainerRepo.Delete(trainer);
            Repos.DbHundler.Save();
            var trainerDto = Mapper.Map<Trainer, TrainerDto>(trainer);
            return Ok(trainerDto);
        }
        [HttpGet]
        public IHttpActionResult Get(int id)
        {
            var trainer = Repos.trainerRepo.GetEmpty(id);
            if (trainer == null)
                return NotFound();
            var trainerDto = Mapper.Map<Trainer, TrainerDto>(trainer);
            return Ok(trainerDto);
        }
        [HttpGet]
        public IHttpActionResult GetAll()
        {
            var trainers = Repos.trainerRepo.GetAllEmpty().Select(Mapper.Map<Trainer, TrainerDto>);
            return Ok(trainers);
        }
        [HttpPut]
        public IHttpActionResult Update(int id, TrainerDto trainerDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var trainer = Repos.trainerRepo.Get(id);
            if (trainer == null)
                return NotFound();
            Mapper.Map(trainerDto, trainer);
            Repos.DbHundler.Save();
            return StatusCode(HttpStatusCode.NoContent);
        }
        [Route("api/Trainers/RemoveCourse"), HttpPost]
        public async Task<IHttpActionResult> RemoveCourseAsync([FromBody] TrainerCourseData data)
        {
            if (data.trainerId == null || data.courseId == null)
                return BadRequest();
            Trainer trainer = Repos.trainerRepo.Get(data.trainerId);
            Course course = Repos.courseRepo.Get(data.courseId);
            if (trainer == null || course == null)
                return BadRequest();

            trainer.Courses.Remove(course);
            course.Trainer = null;

            if (ModelState.IsValid)
            {
                Repos.trainerRepo.Update(trainer);
                Repos.courseRepo.Update(course);
                _ = await Repos.DbHundler.SaveAsync();
                return Ok(200);
            }
            return BadRequest("Record Failed");
        }
        [Route("api/Trainers/AddCourse"), HttpPost]
        public async Task<IHttpActionResult> AddCoursesAsync([FromBody] List<TrainerCourseData> data)
        {
            if (data.Count == 0)
                return BadRequest("data.Count == 0");
            var trainer = Repos.trainerRepo.GetEmpty(data[0].trainerId);
            if (trainer == null)
                return BadRequest("assignment == null");
            var coursesIds = data.Select(d => d.courseId).ToList();
            var courses = Repos.courseRepo.GetAllByIdsEmpty(coursesIds);
            foreach (var course in courses)
            {
                trainer.Courses.Add(course);
            }
            _ = await Repos.DbHundler.SaveAsync();
            return Ok(200);
        }
    }
}

Assignment_2_(MVC)_CodeFirst/Controllers/CoursesController.cs
using Assignment_2__MVC__CodeFirst.Models.Entities;
using Assignment_2__MVC__CodeFirst.Repositories;
using Assignment_2__MVC__CodeFirst.Static;
using Assignment_2__MVC__CodeFirst.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Assignment_2__MVC__CodeFirst.Controllers
{
    public class CoursesController : Controller
    {
        private Repos _repositories;
        private CourseRepo _courseRepo;
        private SchoolRepo _schoolRepo;
        private TrainerRepo _trainerRepo;
        private StudentRepo _studentRepo;
        public CoursesController(IRepos repo)
        {
            this._repositories = (Repos)repo;
            this._courseRepo = this._repositories.Courses;
            this._schoolRepo = this._repositories.Schools;
            this._trainerRepo = this._repositories.Trainers;
            this._studentRepo = this._repositories.Students;
        }
        // GET: Courses
        public ActionResult Index()
        {
            return View(this._courseRepo.GetAll());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(string Search)
        {
            if (Search != null && Search.Length > 0)
                return View(this._courseRepo.GetAllByName(Search));
            else
                return View(this._courseRepo.GetAll());
        }

        // GET: Courses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = this._courseRepo.Get(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // GET: Courses/Create
        public ActionResult Create(int schoolId)
        {
            var schools = new SelectList(this._schoolRepo.GetAll(), "ID", "Name");
            var trainers = new SelectList(this._trainerRepo.GetAllBySchool(schoolId), "ID", "FullName");
            List<SelectListItem> studentsSelectListItems = new List<SelectListItem>();
            foreach (Student student in this._studentRepo.GetAllBySchool(schoolId))
            {
                SelectListItem selectList = new SelectListItem()
                {
                    Text = student.FullName,
                    Value = student.ID.ToString()
                };
                studentsSelectListItems.Add(selectList);
            }

            CourseViewModel courseView = new CourseViewModel()
            {
                SelectedStudents = new List<int>(),
                Students = studentsSelectListItems,
                SchoolId = schoolId,
                Schools = schools,
                Trainers = trainers
            };

            return View(courseView);
        }

        // POST: Courses/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CourseViewModel courseView)
        {
            Course course = new Course();
            course.Title = courseView.Title;
            course.StartDate = courseView.StartDate;
            course.EndDate = courseView.EndDate;
            course.School = this._schoolRepo.Get(courseView.SchoolId);
            course.Trainer = this._trainerRepo.Get(courseView.TrainerId);
            if (courseView.SelectedStudents != null)
            {
                var students = this._studentRepo.GetAllBySchool(course.School.ID);
                foreach (var id in courseView.SelectedStudents)
                {
                    var selectedStudent = this._studentRepo.Get(id);
                    if (students.Contains(selectedStudent))
                    {
                        if (course.Students != null)
                        {
                            course.Students.Add(selectedStudent);
                        }
                        else
                        {
                            course.Students = new List<Student>();
                            course.Students.Add(selectedStudent);
                        }
                    } 
                }
            }

            if (ModelState.IsValid)
            {
                this._courseRepo.Add(course);
                this._courseRepo.Save();
                return RedirectToAction("Details", "Schools", new { id = course.School.ID });
            }

            return View(courseView);
        }

        // GET: Courses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Course course = this._courseRepo.Get(id);
            if (course == null)
                return HttpNotFound();

            var schools = new SelectList(this._schoolRepo.GetAll(), "ID", "Name");
            var selectedSchool = schools.FirstOrDefault(x => int.Parse(x.Value) == course.ID);
            if (selectedSchool != null) selectedSchool.Selected = true;

            var trainers = new SelectList(this._trainerRepo.GetAllBySchool(course.School.ID), "ID", "FullName");
            var selectedTrainer = trainers.FirstOrDefault(x => int.Parse(x.Value) == course.ID);
            if (selectedTrainer != null) selectedTrainer.Selected = true;

            List<SelectListItem> studentsSelectListItems = new List<SelectListItem>();
            foreach (Student student in this._studentRepo.GetAllBySchool(course.School.ID))
            {
                SelectListItem selectList = new SelectListItem()
                {
                    Text = student.FullName,
                    Value = student.ID.ToString()
                };
                if (!course.Students.Contains(student))
                    studentsSelectListItems.Add(selectList);
            }

            CourseViewModel courseView = new CourseViewModel()
            {
                ID = course.ID,
                Title = course.Title,
                StartDate = course.StartDate,
                EndDate = course.EndDate,
                SchoolId = course.School.ID,
                TrainerId = course.Trainer.ID,
                SelectedStudents = new List<int>(),
                MyStudents = course.Students,
                Students = studentsSelectListItems,
                Schools = schools,
                Trainers = trainers
            };

            return View(courseView);
        }

        // POST: Courses/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CourseViewModel courseView)
        {
            Course courseDB = this._courseRepo.Get(courseView.ID);
            courseDB.Title = courseView.Title;
            courseDB.StartDate = courseView.StartDate;
            courseDB.EndDate = courseView.EndDate;
            courseDB.School = this._schoolRepo.Get(courseView.SchoolId);
            courseDB.Trainer = this._trainerRepo.Get(courseView.TrainerId);
            if(courseView.SelectedStudents != null)
            {
                var students = this._studentRepo.GetAllBySchool(courseDB.School.ID);
                foreach(var id in courseView.SelectedStudents)
                {
                    var selectedStudent = this._studentRepo.Get(id);
                    if (students.Contains(selectedStudent))
                        courseDB.Students.Add(selectedStudent);
                }
            }

            if (ModelState.IsValid)
            {
                this._courseRepo.Update(courseDB);
                this._courseRepo.Save();
                return RedirectToAction("Details", "Schools", new { id = courseDB.School.ID });
            }

            var schools = new SelectList(this._schoolRepo.GetAll(), "ID", "Name");
            var selectedSchool = schools.FirstOrDefault(x => int.Parse(x.Value) == courseDB.ID);
            if (selectedSchool != null) selectedSchool.Selected = true;

            var trainers = new SelectList(this._trainerRepo.GetAllBySchool(courseDB.School.ID), "ID", "FullName");
            var selectedTrainer = trainers.FirstOrDefault(x => int.Parse(x.Value) == courseDB.ID);
            if (selectedTrainer != null) selectedTrainer.Selected = true;

            List<SelectListItem> studentsSelectListItems = new List<SelectListItem>();
            foreach (Student student in this._studentRepo.GetAllBySchool(courseDB.School.ID))
            {
                SelectListItem selectList = new SelectListItem()
                {
                    Text = student.FullName,
                    Value = student.ID.ToString()
                };
                if (!courseDB.Students.Contains(student))
                    studentsSelectListItems.Add(selectList);
            }

            CourseViewModel courseView2 = new CourseViewModel()
            {
                ID = courseDB.ID,
                Title = courseDB.Title,
                StartDate = courseDB.StartDate,
                EndDate = courseDB.EndDate,
                SchoolId = courseDB.School.ID,
                TrainerId = courseDB.Trainer.ID,
                SelectedStudents = new List<int>(),
                MyStudents = courseDB.Students,
                Students = studentsSelectListItems,
                Schools = schools,
                Trainers = trainers
            };

            return View(courseView2);
        }

        // GET: Courses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course course = this._courseRepo.Get(id);
            if (course == null)
            {
                return HttpNotFound();
            }
            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

Assignment_2_(MVC)_CodeFirst/Views/Trainers/Create.cshtml
@model Assignment_2__MVC__CodeFirst.ViewModels.TrainerViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Trainer</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SchoolId, "School", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.SchoolId, new SelectList(Assignment_2__MVC__CodeFirst.Static.Repos.schoolRepo.GetAll(), "ID", "Name") as SelectList, "Select School", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.SchoolId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" onclick="loadingShow();"/>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back", "Details", "Schools", new { id = @Model.SchoolId }, new { onclick= "loadingShow();" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Assignment_2_(MVC)_CodeFirst/Views/Trainers/Delete.cshtml
@model Assignment_2__MVC__CodeFirst.Models.Entities.Trainer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Trainer</h4>
    <hr />
    <div class="container">

        <div class="row">
            <div class="col-md-3">
                @Html.DisplayNameFor(model => model.FirstName)
            </div>

            <div class="col-md-9">
                @Html.DisplayFor(model => model.FirstName)
            </div>
        </div>

        <div class="row">
            <div class="col-md-3">
                @Html.DisplayNameFor(model => model.LastName)
            </div>

            <div class="col-md-9">
                @Html.DisplayFor(model => model.LastName)
            </div>
        </div>

        <div class="row">
            <div class="col-md-3">
                @Html.DisplayNameFor(model => model.StartDate)
            </div>

            <div class="col-md-9">
                @Html.DisplayFor(model => model.StartDate)
            </div>
        </div>

    </div>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Delete" class="btn btn-default" /> | 
    @Html.ActionLink("Back", "Details", "Schools", new { Id = @Model.School.ID }, new { onclick = "loadingShow();" })
</div>
    }
</div>

Assignment_2_(MVC)_CodeFirst/Views/Trainers/Details.cshtml
@model Assignment_2__MVC__CodeFirst.Models.Entities.Trainer

@{
    ViewBag.Title = "Details";
}

<h2>@Model.FullName</h2>

<div>
    <h4>Trainer</h4>
    <hr />
    <div class="container">

        <div class="ditails-form text-center">
            <div class="row">
                <div class="col-md-3">
                    <label class="font-weight-bold">@Html.DisplayNameFor(model => model.FullName):</label>
                </div>

                <div class="col-md-9">
                    @Html.DisplayFor(model => model.FullName)
                </div>
            </div>

            <div class="row">
                <div class="col-md-3">
                    <label class="font-weight-bold">@Html.DisplayNameFor(model => model.StartDate):</label>
                </div>

                <div class="col-md-9">
                    @Html.DisplayFor(model => model.StartDate)
                </div>
            </div>

            <div class="row">
                <div class="col-md-3">
                    <label class="font-weight-bold">@Html.DisplayNameFor(model => model.School):</label>
                </div>
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.School.Name)
                </div>
            </div>
        </div>
        

        <br />

        <div class="row">
            <div>
                <label class="font-weight-bold">@Html.DisplayNameFor(model => model.Courses):</label>
                <div class="table-responsive" style="margin-top: 11px;">
                    <table class="table table-striped table-hover">
                        @foreach (var c in Model.Courses)
                        {
                            <tr class="text-center" scope="row">
                                <td scope="col">@Html.ActionLink(c.Title, "Details", "Courses", new { id = c.ID }, new { onclick= "loadingShow();" })</td>
                                <td scope="col">
                                    @Html.ActionLink("Edit", "Edit", "Courses", new { id = c.ID }, new { onclick = "loadingShow();" }) | 
                                    @Html.ActionLink("Delete", "Delete", "Courses", new { id = c.ID }, new { onclick = "loadingShow();" })
                                </td>
                            </tr>
                        }
                    </table>
                </div>
            </div>
        </div>

        <br />

    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }, new { onclick = "loadingShow();" }) |
        @Html.ActionLink("Back", "Details", "Schools", new { id = @Model.School.ID }, new { onclick = "loadingShow();" })
    </p>

Assignment_2_(MVC)_CodeFirst/Views/Trainers/Edit.cshtml
@model Assignment_2__MVC__CodeFirst.ViewModels.TrainerViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal container text-center">
    <h4>Trainer</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)

    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SchoolId, "School", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.SchoolId, @Model.Schools as SelectList, "Select School", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.SchoolId, "", new { @class = "text-danger" })
        </div>
    </div>

    <br />

    <div class="form-group">
        @Html.LabelFor(model => model.Courses, "Courses", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <table>
                @foreach (var c in Model.MyCourses)
                {
                    <tr>
                        <td>@Html.ActionLink(c.Title, "Details", "Courses", new { id = c.ID }, new { @class = "main-col", onclick = "loadingShow();" }) &emsp;&emsp;</td>
                        <td>
                            <div onclick="removeCourseFromTrainer(@Model.ID, @c.ID);" style="float: right;"><a>Remove</a></div>
                            <script type="text/javascript">
                                function removeCourseFromTrainer(trainerId, courseId) {
                                    bootbox.confirm("Are you sure you want to delete?", function (result) {
                                        if (result) {
                                            $.ajax({
                                                type: "POST",
                                                url: "../../api/Trainers/RemoveCourse",
                                                contentType: "application/json; charset=utf-8",
                                                dataType: "json",
                                                data: JSON.stringify(
                                                    {
                                                        "trainerId": trainerId,
                                                        "courseId": courseId
                                                    }
                                                )
                                            }).done(function (data) {
                                                loadingShow();
                                                location.reload();
                                            }).fail(function (error) {
                                                console.log(`Error: ${error}`);
                                            });
                                        }
                                    });
                                };
                            </script>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>

    <br />

    <div class="form-group">
        @Html.LabelFor(model => model.SelectedCourses, "Add Courses", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.ListBoxFor(model => model.SelectedCourses, Model.Courses, new { @class = "form-control", @id = "selectedCoursesListTr" })
            @Html.ValidationMessageFor(model => model.SelectedCourses, "", new { @class = "text-danger" })
            <br />
            <div style="width: 30%;">
                <button onclick="AddCoursesToTrainer(@Model.ID); return false;" style="float:right;" class="btn btn-primary">Add</button>
                <script type="text/javascript">
                    function AddCoursesToTrainer(trainerId) {
                        var courses = [];
                        var listBox = $("#selectedCoursesListTr")[0];
                        for (var i = 0; i < listBox.options.length; i++) {
                            if (listBox.options[i].selected) {
                                var text = listBox.options[i].innerHTML;
                                var value = listBox.options[i].value;
                                courses.push(
                                    {
                                        "trainerId": trainerId,
                                        "courseId": value
                                    }
                                );
                            }
                        }
                        if (courses.length > 0) {
                            $.ajax({
                                type: "POST",
                                url: "../../api/Trainers/AddCourse",
                                contentType: "application/json; charset=utf-8",
                                dataType: "json",
                                data: JSON.stringify(courses)
                            }).done(function (data) {
                                loadingShow();
                                location.reload();
                            }).fail(function (error) {
                                console.log(`Error: ${error}`);
                            });
                        }
                    };
                </script>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" onclick="loadingShow();"/>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back", "Details", "Schools", new { Id = @Model.SchoolId }, new { onclick = "loadingShow();" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Assignment_2_(MVC)_CodeFirst/Views/Trainers/Index.cshtml
@model IEnumerable<Assignment_2__MVC__CodeFirst.Models.Entities.Trainer>

@{
    ViewBag.Title = "Index";
}

<h2>Trainers</h2>

<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Index", "Trainers", FormMethod.Post))
        {
            @Html.AntiForgeryToken();
            @Html.TextBox("Search", "", "", new { placeholder = "Search", @class = "form-input" });
            <input type="submit" name="SaveButton" value="Save" />
        }
    </div>
    <div class="col-md-6">
        <p>
            @Html.ActionLink("Create New", "Create", null, new { onclick = "loadingShow();" })
        </p>
    </div>
</div>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.FullName, "Details", new { id = item.ID }, new { onclick = "loadingShow();" })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }, new { onclick = "loadingShow();" }) | 
            @Html.ActionLink("Delete", "Delete", new { id=item.ID }, new { onclick = "loadingShow();" })
        </td>
    </tr>
}

</table>