Assignment_2_(MVC)_CodeFirst/Models/Entities/Assignment.cs
using Assignment_2__MVC__CodeFirst.CustomAnotations;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Assignment_2__MVC__CodeFirst.Models.Entities
{
    public class Assignment : IEntity
    {
        public int ID { get; set; }

        [Required]
        [MinLength(5)]
        public string Title { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true)]
        //[CurrentDate(ErrorMessage = "Date must be after or equal to current date")]
        public DateTime StartDate { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true)]
        [DateBigger(AddMonths = 1, ErrorMessage = "Date must be smaller than date")]
        public DateTime EndDate { get; set; }

        public ICollection<Student> Students { get; set; } = new List<Student>();

        [Required]
        public School School { get; set; }
    }
}

Assignment_2_(MVC)_CodeFirst/ViewModels/AssignmentViewModel.cs
using Assignment_2__MVC__CodeFirst.CustomAnotations;
using Assignment_2__MVC__CodeFirst.Models.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Assignment_2__MVC__CodeFirst.ViewModels
{
    public class AssignmentViewModel
    {
        public int ID { get; set; }
        public string Title { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime StartDate { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DateBigger(AddMonths = 1, ErrorMessage = "Date must be smaller than date")]
        public DateTime EndDate { get; set; }
        public IEnumerable<int> SelectedStudents { get; set; }
        public IEnumerable<Student> MyStudents { get; set; }
        public IEnumerable<SelectListItem> Students { get; set; }
        public int SchoolId { get; set; }
        public SelectList Schools { get; set; }
    }
}

Assignment_2_(MVC)_CodeFirst/Controllers/Api/AssignmentsController.cs
using Assignment_2__MVC__CodeFirst.Models.Dto;
using Assignment_2__MVC__CodeFirst.Models.Entities;
using Assignment_2__MVC__CodeFirst.Models.Other;
using Assignment_2__MVC__CodeFirst.Static;
using AutoMapper;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Http;

namespace Assignment_2__MVC__CodeFirst.Controllers.Api
{
    public class AssignmentsController : ApiController, IMyController<IHttpActionResult, AssignmentDto>
    {
        [HttpPost]
        public IHttpActionResult Create(AssignmentDto assignmentDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var assignment = Mapper.Map<AssignmentDto, Assignment>(assignmentDto);
            Repos.assignmentRepo.Add(assignment);
            Repos.DbHundler.Save();
            return Ok(assignmentDto);
        }
        [HttpDelete]
        public IHttpActionResult Delete(int id)
        {
            var assignment = Repos.assignmentRepo.Get(id);
            if (assignment == null)
                return NotFound();
            Repos.assignmentRepo.Delete(assignment);
            Repos.DbHundler.Save();
            var assignmentDto = Mapper.Map<Assignment, AssignmentDto>(assignment);
            return Ok(assignmentDto);
        }
        [HttpGet]
        public IHttpActionResult Get(int id)
        {
            var assignment = Repos.assignmentRepo.GetEmpty(id);
            if (assignment == null)
                return NotFound();
            var assignmentDto = Mapper.Map<Assignment, AssignmentDto>(assignment);
            return Ok(assignmentDto);
        }
        [HttpGet]
        public IHttpActionResult GetAll()
        {
            var assignments = Repos.assignmentRepo.GetAllEmpty().Select(Mapper.Map<Assignment, AssignmentDto>);
            return Ok(assignments);
        }
        [HttpPut]
        public IHttpActionResult Update(int id, AssignmentDto assignmentDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();
            var assignment = Repos.assignmentRepo.Get(id);
            if (assignment == null)
                return NotFound();
            Mapper.Map(assignmentDto, assignment);
            Repos.DbHundler.Save();
            return StatusCode(HttpStatusCode.NoContent);
        }
        [Route("api/Assignments/RemoveStudent"), HttpPost]
        public async Task<IHttpActionResult> RemoveStudentAsync([FromBody] AssignmentStudentData data)
        {
            if (data.assignmentId == null || data.studentId == null)
                return BadRequest();
            Assignment assignment = Repos.assignmentRepo.Get(data.assignmentId);
            Student student = Repos.studentRepo.Get(data.studentId);
            if (assignment == null || student == null)
                return BadRequest();

            assignment.Students.Remove(student);
            student.Assignments.Remove(assignment);

            if (ModelState.IsValid)
            {
                Repos.assignmentRepo.Update(assignment);
                Repos.studentRepo.Update(student);
                _ = await Repos.DbHundler.SaveAsync();
                return Ok(200);
            }

            return BadRequest("Record Failed");
        }
        [Route("api/Assignments/AddStudents"), HttpPost]
        public async Task<IHttpActionResult> AddStudentsAsync([FromBody] List<AssignmentStudentData> data)
        {
            if (data.Count == 0)
                return BadRequest("data.Count == 0");
            var assignment = Repos.assignmentRepo.GetEmpty(data[0].assignmentId);
            if (assignment == null)
                return BadRequest("assignment == null");
            var studentsIds = data.Select(d => d.studentId).ToList();
            var students = Repos.studentRepo.GetAllByIdsEmpty(studentsIds);
            foreach (var student in students)
            {
                assignment.Students.Add(student);
            }
            _ = await Repos.DbHundler.SaveAsync();
            return Ok(200);
        }
    }
}

Assignment_2_(MVC)_CodeFirst/Controllers/StudentsController.cs
using Assignment_2__MVC__CodeFirst.Models.Entities;
using Assignment_2__MVC__CodeFirst.Repositories;
using Assignment_2__MVC__CodeFirst.Static;
using Assignment_2__MVC__CodeFirst.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Assignment_2__MVC__CodeFirst.Controllers
{
    public class StudentsController : Controller
    {
        private Repos _repositories;
        private SchoolRepo _schoolRepo;
        private StudentRepo _studentRepo;
        private CourseRepo _courseRepo;
        private AssignmentRepo _assignmentRepo;
        public StudentsController(IRepos repo)
        {
            this._repositories = (Repos)repo;
            this._schoolRepo = this._repositories.Schools;
            this._studentRepo = this._repositories.Students;
            this._courseRepo = this._repositories.Courses;
            this._assignmentRepo = this._repositories.Assignments;
        }
        // GET: Students
        public ActionResult Index()
        {
            return View(this._studentRepo.GetAll());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(string Search)
        {
            if (Search != null && Search.Length > 0)
                return View(this._studentRepo.GetAllByName(Search));
            else
                return View(this._studentRepo.GetAll());
        }

        // GET: Students/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = this._studentRepo.Get(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // GET: Students/Create
        public ActionResult Create(int schoolId)
        {
            var schools = new SelectList(this._schoolRepo.GetAll(), "ID", "Name");
            List<SelectListItem> coursesSelectListItems = new List<SelectListItem>();
            foreach (Course course in this._courseRepo.GetAllBySchool(schoolId))
            {
                SelectListItem selectList = new SelectListItem()
                {
                    Text = course.Title,
                    Value = course.ID.ToString()
                };
                coursesSelectListItems.Add(selectList);
            }
            List<SelectListItem> assignmentSelectListItems = new List<SelectListItem>();
            foreach (Assignment assignment in this._assignmentRepo.GetAllBySchool(schoolId))
            {
                SelectListItem selectList = new SelectListItem()
                {
                    Text = assignment.Title,
                    Value = assignment.ID.ToString()
                };
                assignmentSelectListItems.Add(selectList);
            }
            StudentViewModel studentView = new StudentViewModel()
            {
                SelectedCourses = new List<int>(),
                SelectedAssignments = new List<int>(),
                Courses = coursesSelectListItems,
                Assignments = assignmentSelectListItems,
                Schools = schools,
                SchoolId = schoolId
            };
            return View(studentView);
        }

        // POST: Students/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(StudentViewModel studentView)
        {
            Student student = new Student();
            student.FirstName = studentView.FirstName;
            student.LastName = studentView.LastName;
            student.StartDate = studentView.StartDate;
            student.School = this._schoolRepo.Get(studentView.SchoolId);
            if (studentView.SelectedCourses != null)
            {
                var courses = this._courseRepo.GetAllBySchool(student.School.ID);
                foreach (var id in studentView.SelectedCourses)
                {
                    var selectedCourse = this._courseRepo.Get(id);
                    if (courses.Contains(selectedCourse))
                    { 
                        if (student.Courses != null)
                        {
                            student.Courses.Add(selectedCourse);
                        } 
                        else
                        {
                            student.Courses = new List<Course>();
                            student.Courses.Add(selectedCourse);
                        }
                    }
                        
                }
            }
            if (studentView.SelectedAssignments != null)
            {
                var assignments = this._assignmentRepo.GetAllBySchool(student.School.ID);
                foreach (var id in studentView.SelectedAssignments)
                {
                    var selectedAssignment = this._assignmentRepo.Get(id);
                    if (assignments.Contains(selectedAssignment))
                    {
                        if (student.Assignments != null)
                        {
                            student.Assignments.Add(selectedAssignment);
                        }
                        else
                        {
                            student.Assignments = new List<Assignment>();
                            student.Assignments.Add(selectedAssignment);
                        }
                    }
                        
                }
            }
            if (ModelState.IsValid)
            {
                this._studentRepo.Add(student);
                this._studentRepo.Save();
                return RedirectToAction("Details", "Schools", new { id = student.School.ID });
            }
            return View(studentView);
        }

        // GET: Students/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Student student = this._studentRepo.Get(id);
            if (student == null)
                return HttpNotFound();

            var schools = new SelectList(this._schoolRepo.GetAll(), "ID", "Name");
            var selectedSchool = schools.FirstOrDefault(x => int.Parse(x.Value) == student.ID);
            if (selectedSchool != null) selectedSchool.Selected = true;

            List<SelectListItem> coursesSelectListItems = new List<SelectListItem>();
            foreach( Course course in this._courseRepo.GetAllBySchool(student.School.ID) )
            {
                SelectListItem selectList = new SelectListItem()
                {
                    Text = course.Title,
                    Value = course.ID.ToString()
                };
                if (!student.Courses.Contains(course))
                    coursesSelectListItems.Add(selectList);
            }

            List<SelectListItem> assignmentSelectListItems = new List<SelectListItem>();
            foreach (Assignment assignment in this._assignmentRepo.GetAllBySchool(student.School.ID))
            {
                SelectListItem selectList = new SelectListItem()
                {
                    Text = assignment.Title,
                    Value = assignment.ID.ToString()
                };
                if(!student.Assignments.Contains(assignment))    
                    assignmentSelectListItems.Add(selectList);
            }

            StudentViewModel studentView = new StudentViewModel()
            {
                ID = student.ID,
                FirstName = student.FirstName,
                LastName = student.LastName,
                StartDate = student.StartDate,
                SchoolId = student.School.ID,
                SelectedCourses = new List<int>(),
                SelectedAssignments = new List<int>(),
                Courses = coursesSelectListItems,
                Assignments = assignmentSelectListItems,
                Schools = schools,
                MyCourses = student.Courses,
                MyAssignments = student.Assignments
            };
            return View(studentView);
        }

        // POST: Students/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(StudentViewModel studentView)
        {
            Student studentDB = this._studentRepo.Get(studentView.ID);
            studentDB.FirstName = studentView.FirstName;
            studentDB.LastName = studentView.LastName;
            studentDB.StartDate = studentView.StartDate;
            studentDB.School = this._schoolRepo.Get(studentView.SchoolId);
            if(studentView.SelectedCourses != null)
            {
                var courses = this._courseRepo.GetAll();
                foreach (var id in studentView.SelectedCourses)
                {
                    var selectedCourse = this._courseRepo.Get(id);
                    if (courses.Contains(selectedCourse))
                        studentDB.Courses.Add(selectedCourse);
                }
            }
            if (studentView.SelectedAssignments != null)
            {
                var assignments = this._assignmentRepo.GetAll();
                foreach (var id in studentView.SelectedAssignments)
                {
                    var selectedAssignment = this._assignmentRepo.Get(id);
                    if (assignments.Contains(selectedAssignment))
                        studentDB.Assignments.Add(selectedAssignment);
                }
            }

            if (ModelState.IsValid)
            {
                this._studentRepo.Update(studentDB);
                this._studentRepo.Save();
                return RedirectToAction("Details", "Schools", 
                    new { id = studentDB.School.ID });
            }

            var schools = new SelectList(this._schoolRepo.GetAll(), "ID", "Name");
            var selectedSchool = schools.FirstOrDefault(x => int.Parse(x.Value) == studentDB.ID);

Assignment_2_(MVC)_CodeFirst/Views/Assignments/Create.cshtml
@model Assignment_2__MVC__CodeFirst.ViewModels.AssignmentViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Assignment</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SchoolId, "School", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.SchoolId, Model.Schools as SelectList, "Select School", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.SchoolId, "", new { @class = "text-danger" })
        </div>
    </div>

    <br />

    <div class="form-group">
        @Html.LabelFor(model => model.SelectedStudents, "Add Student", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.ListBoxFor(model => model.SelectedStudents, Model.Students, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.SelectedStudents, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" onclick="loadingShow();"/>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back", "Details", "Schools", new { id = @Model.SchoolId }, new { onclick = "loadingShow();" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Assignment_2_(MVC)_CodeFirst/Views/Assignments/Delete.cshtml
@model Assignment_2__MVC__CodeFirst.Models.Entities.Assignment

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Assignment</h4>
    <hr />
    <div class="container">

        <div class="row">
            <div class="col-md-3">
                @Html.DisplayNameFor(model => model.Title)
            </div>

            <div class="col-md-9">
                @Html.DisplayFor(model => model.Title)
            </div>
        </div>

        <div class="row">
            <div class="col-md-3">
                @Html.DisplayNameFor(model => model.StartDate)
            </div>

            <div class="col-md-9">
                @Html.DisplayFor(model => model.StartDate)
            </div>
        </div>

        <div class="row">
            <div class="col-md-3">
                @Html.DisplayNameFor(model => model.EndDate)
            </div>

            <div class="col-md-9">
                @Html.DisplayFor(model => model.EndDate)
            </div>
        </div>

    </div>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Delete" class="btn btn-default" /> |
    @Html.ActionLink("Back", "Details", "Schools", new { Id = @Model.School.ID }, new { onclick = "loadingShow();" })
</div>
    }
</div>

Assignment_2_(MVC)_CodeFirst/Views/Assignments/Details.cshtml
@model Assignment_2__MVC__CodeFirst.Models.Entities.Assignment

@{
    ViewBag.Title = "Details";
}

<h2>@Model.Title</h2>

<div>
    <h4>Assignment</h4>
    <hr />
    <div class="container">

        <div class="ditails-form text-center">
            <div class="row">
                <div class="col-md-3">
                    <label class="font-weight-bold">@Html.DisplayNameFor(model => model.Title):</label>
                </div>

                <div class="col-md-9">
                    @Html.DisplayFor(model => model.Title)
                </div>
            </div>

            <div class="row">
                <div class="col-md-3">
                    <label class="font-weight-bold">@Html.DisplayNameFor(model => model.StartDate):</label>
                </div>

                <div class="col-md-9">
                    @Html.DisplayFor(model => model.StartDate)
                </div>
            </div>

            <div class="row">
                <div class="col-md-3">
                    <label class="font-weight-bold">@Html.DisplayNameFor(model => model.EndDate):</label>
                </div>

                <div class="col-md-9">
                    @Html.DisplayFor(model => model.EndDate)
                </div>
            </div>

            <div class="row">
                <div class="col-md-3">
                    <label class="font-weight-bold">@Html.DisplayNameFor(model => model.School):</label>
                </div>
                <div class="col-md-9">
                    @Html.DisplayFor(model => model.School.Name)
                </div>
            </div>
        </div>
    </div>

        <br />

        <div class="row">
            <div>
                <label class="font-weight-bold">@Html.DisplayNameFor(model => model.Students):</label>
                <div class="table-responsive" style="margin-top: 11px;">
                    <table class="table table-striped table-hover">
                        @foreach (var s in Model.Students)
                        {
                            <tr class="text-center" scope="row">
                                <td scope="col">@Html.ActionLink(s.FullName, "Details", "Students", new { id = s.ID }, new { onclick = "loadingShow();" })&emsp;</td>
                                <td scope="col">
                                    @Html.ActionLink("Edit", "Edit", "Students", new { id = s.ID }, new { onclick = "loadingShow();" }) | 
                                    @Html.ActionLink("Delete", "Delete", "Students", new { id = s.ID }, new { onclick = "loadingShow();" })
                                </td>
                            </tr>
                        }
                    </table>
                </div>
            </div>
        </div>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }, new { onclick = "loadingShow();" }) |
    @Html.ActionLink("Back", "Details", "Schools", new { id = @Model.School.ID }, new { onclick = "loadingShow();" })
</p>

Assignment_2_(MVC)_CodeFirst/Views/Assignments/Index.cshtml
@model IEnumerable<Assignment_2__MVC__CodeFirst.Models.Entities.Assignment>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Index", "Assignments", FormMethod.Post))
        {
            @Html.AntiForgeryToken();
            @Html.TextBox("Search", "", "", new { placeholder = "Search", @class = "form-input" });
            <input type="submit" name="SaveButton" value="Save" />
        }
    </div>
    <div class="col-md-6">
        <p>
            @Html.ActionLink("Create New", "Create", null, new { onclick = "loadingShow();" })
        </p>
    </div>
</div>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.Title, "Details", new { id = item.ID }, new { onclick = "loadingShow();" })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }, new { onclick = "loadingShow();" }) | 
            @Html.ActionLink("Delete", "Delete", new { id=item.ID }, new { onclick = "loadingShow();" })
        </td>
    </tr>
}

</table>